/** @type {import('tailwindcss').Config} */
// Void UI — Tailwind config. Pair with tokens.css.
module.exports = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./pages/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: "var(--bg)",
        "bg-subtle": "var(--bg-subtle)",
        "bg-muted": "var(--bg-muted)",
        surface: "var(--surface)",
        "surface-raised": "var(--surface-raised)",
        border: "var(--border)",
        "border-strong": "var(--border-strong)",
        fg: "var(--fg)",
        "fg-muted": "var(--fg-muted)",
        "fg-subtle": "var(--fg-subtle)",
        accent: "var(--accent)",
        "accent-fg": "var(--accent-fg)",
        "accent-soft": "var(--accent-soft)",
        amethyst: {
          200: "var(--amethyst-200)",
          300: "var(--amethyst-300)",
          400: "var(--amethyst-400)",
          500: "var(--amethyst-500)",
          600: "var(--amethyst-600)",
          700: "var(--amethyst-700)",
          800: "var(--amethyst-800)",
        },
        void: {
          0: "var(--void-000)",
          50: "var(--void-050)",
          100: "var(--void-100)",
          200: "var(--void-200)",
          300: "var(--void-300)",
          400: "var(--void-400)",
          500: "var(--void-500)",
          600: "var(--void-600)",
          700: "var(--void-700)",
          800: "var(--void-800)",
          900: "var(--void-900)",
          950: "var(--void-950)",
        },
      },
      fontFamily: {
        mono: ["var(--font-mono)"],
        dot: ["var(--font-dot)"],
        sans: ["var(--font-sans)"],
      },
      fontSize: {
        xs: "var(--text-xs)",
        sm: "var(--text-sm)",
        base: "var(--text-base)",
        md: "var(--text-md)",
        lg: "var(--text-lg)",
        xl: "var(--text-xl)",
        "2xl": "var(--text-2xl)",
        "3xl": "var(--text-3xl)",
        "4xl": "var(--text-4xl)",
        hero: "var(--text-hero)",
      },
      letterSpacing: {
        tight: "var(--tracking-tight)",
        wide: "var(--tracking-wide)",
        mega: "var(--tracking-mega)",
      },
      borderRadius: {
        none: "0",
        xs: "var(--radius-1)",
        sm: "var(--radius-2)",
        md: "var(--radius-3)",
        pill: "var(--radius-pill)",
      },
      transitionTimingFunction: {
        snap: "var(--ease-snap)",
      },
      transitionDuration: {
        fast: "120ms",
        med: "180ms",
      },
    },
  },
  plugins: [],
};
